Eda pdf fix
dod-advana/gamechanger-web pull request #11
Opened 2021-05-28 17:26 UTC by babalolak

Must add EDA_DATA_HOST to backend/.env.

2021-05-28 18:47 UTC, aaron42051 approved these changes

2021-06-02 15:22 UTC, JLyons1985 commented on backend/node_app/config/constants.js
> +	GAMECHANGER_BACKEND_EDA_URL: `http://${process.env.EDA_DATA_HOST}:8990`,
Can you add the EDA_DATA_HOST to the env.template file as well as to the confluence page that has the .env file that way we know to include the right stuff into the deployments?

2021-06-02 15:24 UTC, JLyons1985 requested changes
In the constants.j file you reference env.EDA_DATA_HOST. Can you ensure that is added to the env.template file as well as in confluence as well please. This will ensure we are tracking the right stuff for deployments.

2021-06-03 17:24 UTC, JLyons1985 approved these changes

2021-06-03 17:25 UTC, merged