UOT-102614 EDA Add Issue Office MAJCOM/DoDAAC Name Filters
dod-advana/gamechanger-web pull request #124
Opened 2021-07-22 23:40 UTC by aaron42051

https://confluence.di2e.net/pages/viewpage.action?pageId=1295428532

2021-07-23 13:02 UTC, JLyons1985 requested changes
Left in a console log. Fix that and you will be good.

2021-07-23 13:02 UTC, JLyons1985 commented on backend/node_app/modules/eda/edaSearchUtility.js
> +			console.log(JSON.stringify(query))
Left in a log

2021-07-23 16:35 UTC, aaron42051 commented on backend/node_app/modules/eda/edaSearchUtility.js
> +			console.log(JSON.stringify(query))
fixed!

2021-07-26 13:30 UTC, JLyons1985 approved these changes

2021-07-26 13:30 UTC, merged