added endpoint for getting doc ingest stats
dod-advana/gamechanger-web pull request #382
Opened 2022-03-03 14:39 UTC by drospond

## Description

Adds an end point for getting document ingestion stats. Will be used for a graph and data display on the DST.

## !vibez

Almost done with these DST updates, aaaah yeah. 

## Related Issue/Ticket
Main Ticket: [UOT-130401](https://jira.di2e.net/browse/UOT-130401)
Related Ticket: [UOT-130405](https://jira.di2e.net/browse/UOT-130405)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Smoke testing instructions

The new endpoint is '/api/gameChanger/getDocIngestionStats'. Should get results like:
```
 {
	docsByMonth: [{Feb: 17598}],
	numberOfSources: 3,    
	numberOfDocuments: 111263
}
```
Will need to point to RDS. Some of the data and tables won't exist on your local

## Checklist:

- [ ] Documentation updated
- [x] Unit tests added/updated
- [ ] Smoke testing relevant to authentication needed
- [ ] Clones involved and accounted for
- [ ] RDS migrations or other data manipulation necessary
- [ ] Dev tools or other infrastructure changed

2022-03-07 17:35 UTC, JLyons1985 submitted a review, later dismissed

2022-03-07 19:59 UTC, gernerBAH requested changes
Please rewrite the endpoint as a get w/query params instead of a post. We're not updating any data with this request.

2022-03-08 21:07 UTC, JLyons1985 approved these changes

2022-03-09 17:06 UTC, JLyons1985 approved these changes

2022-03-09 17:06 UTC, merged