changed process to use thread id as keys
dod-advana/gamechanger-web pull request #391
Opened 2022-03-08 16:18 UTC by JaredJRoss

## Description

Changed process on ml-api to use the thread id instead of name as key so reflected that in the admin table

## !vibez

Chilling
## Related Issue/Ticket

https://jira.di2e.net/browse/UOT-132221
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ X] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Smoke testing instructions

Go to the admin dashboard and start a process.  Make sure also that you can stop one if needed 
## Checklist:

- [ ] Documentation updated
- [ ] Unit tests added/updated
- [ ] Smoke testing relevant to authentication needed
- [ ] Clones involved and accounted for
- [ ] RDS migrations or other data manipulation necessary
- [ ] Dev tools or other infrastructure changed

2022-03-08 21:05 UTC, JLyons1985 submitted a review, later dismissed

2022-03-10 16:15 UTC, drospond requested changes
Just needs dev merged in. A lot of missing semi colon errors on compile.

2022-03-10 16:43 UTC, rha930 approved these changes

2022-03-10 18:24 UTC, drospond approved these changes

2022-03-10 18:24 UTC, merged