Uot 99685 html open
dod-advana/gamechanger-web pull request #40
Opened 2021-06-09 19:39 UTC by taylormadehdz

html open in cards. open doesnt work locally so pointed to 10.194.9.112:8990 for testing

2021-06-11 16:31 UTC, JLyons1985 requested changes
Fix all the spacing here. Lint issues are important, keeps code readable and clean. Other than that its good.

2021-06-11 16:31 UTC, JLyons1985 commented on frontend/src/components/documentViewer/PDFViewer.js
> +    const [fileUrl, setFileUrl] = React.useState(null);
Fix the spacing here to keep things lined up please same for line 21

2021-06-11 16:31 UTC, JLyons1985 commented on frontend/src/components/documentViewer/PDFViewer.js
> +    useEffect(() => {
spacing here as well

2021-06-11 16:31 UTC, JLyons1985 commented on frontend/src/components/modules/policy/policyCardHandler.js
> +            return (
Spacing

2021-06-15 19:07 UTC, taylormadehdz commented
<img width="1056" alt="Screen Shot 2021-06-09 at 12 32 21 PM" src="https://user-images.githubusercontent.com/36052099/122109406-94538c00-cdda-11eb-917f-648101d58ce1.png">

2021-06-16 16:10 UTC, JLyons1985 approved these changes

2021-06-16 16:15 UTC, merged