UOT-138571 Remove Related Searches white space, Fix sort function
dod-advana/gamechanger-web pull request #453
Opened 2022-04-05 04:18 UTC by aaron42051

## Description

- change the size of the clickable Related Searches pills to show 2 in 1 row on a 1920x1080 screen
- change the sort and order selections to use the main search (instead of docsPagination)
- allow the search to cancel itself if 2 are made in succession

## !vibez

Took me a long time to understand canceling consecutive calls and how pagination and search were different apis.

## Related Issue/Ticket

https://jira.di2e.net/browse/UOT-138571
https://jira.di2e.net/browse/UOT-138418

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Smoke testing instructions

Use the chrome dev tools to set your screen size to 1920x1080 (can do this by right-click Inspect, then click on the second button from the top left that looks like a phone/tablet). Do a random search and check the related searches. Should show 2 pills to 1 row.

Then choose a source filter, wait 1 second, and then choose a different sort. The results should have both the filter and the sort correctly applied. 

## Checklist:

- [ ] Documentation updated
- [ ] Unit tests added/updated
- [ ] Smoke testing relevant to authentication needed
- [ ] Clones involved and accounted for
- [ ] RDS migrations or other data manipulation necessary
- [ ] Dev tools or other infrastructure changed

2022-04-08 17:03 UTC, JaredJRoss approved these changes

2022-04-08 17:51 UTC, JaredJRoss approved these changes

2022-04-10 17:04 UTC, melodie-bah requested changes
Are the review table fixes part of the bugfix? If not, could those be their own ticket?

Otherwise, this bug fix is good to go.

2022-04-10 17:04 UTC, melodie-bah commented on backend/node_app/migrations/jbook/20220329194330-114-update-review-table.js
> +};
Should this jbook migration be included in this bug fix? Seems unrelated.

2022-04-11 23:50 UTC, melodie-bah approved these changes

2022-04-11 23:50 UTC, merged