Task/uot 142175 - Search Enhancements and Refactoring
dod-advana/gamechanger-web pull request #489
Opened 2022-04-22 19:50 UTC by rha930

## Description

- Document ranking is now impacted by number of hits and all weights have been adjusted
- Fixed partial title matching returning too many results
- MLsearchUtility is separated from searchUtility

## !vibez

## Related Issue/Ticket

https://jira.di2e.net/browse/UOT-142175
https://jira.di2e.net/browse/UOT-142175

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Smoke testing instructions

## Checklist:

- [ ] Documentation updated
- [ ] Unit tests added/updated
- [ ] Smoke testing relevant to authentication needed
- [ ] Clones involved and accounted for
- [ ] RDS migrations or other data manipulation necessary
- [ ] Dev tools or other infrastructure changed

2022-04-25 14:50 UTC, JLyons1985 submitted a review, later dismissed

2022-04-25 17:04 UTC, JaredJRoss requested changes

2022-04-25 17:04 UTC, JaredJRoss commented on backend/node_app/controllers/adminController.js
> +const MLSearchUtility = require('../utils/MLsearchUtility');
MLsearchUtility should be MLSearchUtility

2022-04-25 17:04 UTC, JaredJRoss commented on backend/node_app/modules/policy/policySearchHandler.js
> +const MLSearchUtility = require('../../utils/MLsearchUtility');
MLsearchUtility should be MLSearchUtility

2022-04-25 17:15 UTC, JaredJRoss approved these changes

2022-04-26 15:36 UTC, katerdowdy approved these changes

2022-04-26 15:39 UTC, merged