Task/uot 137808
dod-advana/gamechanger-web pull request #490
Opened 2022-04-22 20:23 UTC by drospond

**Description**
Updates the data status tracker's progress tab mostly.

**!vibez**
Movin' on

**Related Issue/Ticket**
[UOT-137808](https://jira.di2e.net/browse/UOT-137808)

**Types of changes**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Smoke testing instructions**
* Navigate to the Data Status Tracker on the left nav bar. The tool tip and label should now say 'Data Status Tracker' rather than 'Data Tracker'. 
* On the progress tab, the table should be sorted by Source by default. Source should now be the only sortable column. Sort by clicking on the column header. 
* Source should now be filterable as well. Test to make sure it is by typing in the input on the column.
* New column, # DOCUMENTS, added. Make sure it works properly 

**Checklist:**
- [ ] Documentation updated
- [x] Unit tests added/updated
- [ ] Smoke testing relevant to authentication needed
- [ ] Clones involved and accounted for
- [ ] RDS migrations or other data manipulation necessary
- [ ] Dev tools or other infrastructure changed

2022-04-25 14:48 UTC, JLyons1985 requested changes
Just remove that one log and looks fine to me.

2022-04-25 14:48 UTC, JLyons1985 commented on frontend/src/components/dataTracker/GCDataStatusTracker.js
> +			console.log('sorted: ', sorted);
Probably can remove this log.

2022-04-25 18:34 UTC, aaron42051 approved these changes
(I removed the log)

2022-04-26 15:59 UTC, melodie-bah approved these changes

2022-04-26 16:02 UTC, JLyons1985 approved these changes

2022-04-26 16:02 UTC, merged