docker-compose override template
dod-advana/gamechanger-web pull request #6
Opened 2021-05-26 22:25 UTC by smalagon15

On docker build and up if there is a docker-compose.override.yml in the directory then it will override or add to the parameters in the docker-compose.

This adds a gitnore line for docker-compose.override.yml and adds a docker-compose.override.template.yml so it can be renamed for dev purposes.

2021-05-28 13:34 UTC, jram930 commented
@smalagon15 can you just drop this in the normal docker-compose? I don't think we need to add an override for it.

2021-05-28 13:34 UTC, jram930 requested changes
Please move this change into the normal docker-compose.

2021-06-01 18:37 UTC, JLyons1985 approved these changes

2021-06-02 13:23 UTC, JLyons1985 approved these changes

2021-06-02 16:08 UTC, jram930 approved these changes

2021-06-02 16:08 UTC, merged